name: Agent Smoke
on:
  push:
    branches: [ main, develop, feature/** ]
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to test (checked out for this run)
        required: true
        default: main

jobs:
  smoke:
    runs-on: macos-15
    env:
      TZ: Europe/Zurich
      AGENT_MODE: openai
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || 'main' }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install SDK
        run: |
          python -m pip install -U pip
          pip install openai==2.6.1
      - name: Smoke probe
        run: |
          python - <<'PY'
          import os, sys
          from openai import OpenAI
          key = os.getenv("OPENAI_API_KEY")
          if not key or len(key) < 20:
              print("Missing or short OPENAI_API_KEY"); sys.exit(2)
          try:
              client = OpenAI()
              models = client.models.list()
              first = next(iter(models.data), None)
              print("OK first_model:", getattr(first, "id", "none"))
              sys.exit(0 if first else 3)
          except Exception as e:
              print("Probe failure:", e)
              sys.exit(1)
          PY
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: agent-smoke-logs
          path: |
            **/*.log
          if-no-files-found: ignore
