name: Agent Smoke

on:
  push:
    branches: [ main, develop, feature/** ]
  workflow_dispatch:
    inputs:
      scenario:
        description: "Scenario text for the live smoke"
        required: false
        default: "15 guests in November; propose 3–5 evening options 18:00–22:00"
  schedule:
    - cron: "0 */3 * * *"

jobs:
  smoke:
    runs-on: macos-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      AGENT_MODE: openai
      TZ: Europe/Zurich
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install -U pip
      - run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pytest openai
          fi
      - run: bash scripts/preflight_agent_tests.sh
      - run: |
          export OPENAI_TEST_MODE=1
          bash scripts/run_live_openai.sh
      - uses: actions/upload-artifact@v4
        with:
          name: agent-smoke-artifacts
          path: |
            run.log
            tmp-integration/e2e-live-happy-path.jsonl
