name: live-smoke
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to test"
        required: false
        default: main
  push:
    branches: ["**"]
    paths:
      - "tests/e2e/**"
      - "backend/providers/**"
      - ".github/workflows/live-smoke.yml"
      - "Makefile"
jobs:
  run:
    if: ${{ secrets.OPENAI_API_KEY != '' }}
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -e .[test]
      - run: pytest -m live_smoke -q
