name: live-smoke
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to test"
        required: false
        default: main

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # maps secret → env
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      - name: Assert secret present
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "OPENAI_API_KEY secret is missing in repo settings → Secrets and variables → Actions"; exit 1; fi
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -e .[test]
      - run: pytest -m live_smoke -q
